services:
  xrpl_ingestor_testnet:
    build:
      context: .
      args:
        BINARY_NAME: xrpl_ingestor
    deploy:
      mode: replicated
      replicas: 60
    environment:
      - NETWORK=testnet
      - ENVIRONMENT=production

  xrpl_distributor_testnet:
    build:
      context: .
      args:
        BINARY_NAME: xrpl_distributor
    environment:
      - NETWORK=testnet
      - ENVIRONMENT=production

  xrpl_ticket_creator_testnet:
    build:
      context: .
      args:
        BINARY_NAME: xrpl_ticket_creator
    environment:
      - NETWORK=testnet
      - ENVIRONMENT=production

  xrpl_includer_testnet:
    build:
      context: .
      args:
        BINARY_NAME: xrpl_includer
    deploy:
      mode: replicated
      replicas: 4
    environment:
      - NETWORK=testnet
      - ENVIRONMENT=production

  xrpl_subscriber_testnet:
    build:
      context: .
      args:
        BINARY_NAME: xrpl_subscriber
    environment:
      - NETWORK=testnet
      - ENVIRONMENT=production

  xrpl_funder_testnet:
    build:
      context: .
      args:
        BINARY_NAME: xrpl_funder
    environment:
      - NETWORK=testnet
      - ENVIRONMENT=production

  price_feed:
    build:
      context: .
      args:
        BINARY_NAME: price_feed
    environment:
      - NETWORK=testnet
      - ENVIRONMENT=production

  proof_retrier:
    build:
      context: .
      args:
        BINARY_NAME: proof_retrier
    environment:
      - NETWORK=testnet
      - ENVIRONMENT=production

  voting_retrier:
    build:
      context: .
      args:
        BINARY_NAME: voting_retrier
    environment:
      - NETWORK=testnet
      - ENVIRONMENT=production

  redis_devnet:
    image: redis:alpine
    container_name: redis_devnet
    ports:
      - "127.0.0.1:6379:6379"

  rabbitmq_devnet:
    image: rabbitmq:3-management
    container_name: rabbitmq_devnet
    environment:
      RABBITMQ_PLUGINS: "rabbitmq_prometheus rabbitmq_management"
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:15692:15692"

  redis_testnet:
    image: redis:alpine
    container_name: redis_testnet
    ports:
      - "127.0.0.1:6380:6379"

  rabbitmq_testnet:
    image: rabbitmq:3-management
    container_name: rabbitmq_testnet
    environment:
      RABBITMQ_PLUGINS: "rabbitmq_prometheus rabbitmq_management"
    ports:
      - "127.0.0.1:5673:5672"
      - "127.0.0.1:15673:15672"
      - "127.0.0.1:15693:15692"

  redis_mainnet:
    image: redis:alpine
    container_name: redis_mainnet
    ports:
      - "127.0.0.1:6380:6379"

  rabbitmq_mainnet:
    image: rabbitmq:3-management
    container_name: rabbitmq_mainnet
    environment:
      RABBITMQ_PLUGINS: "rabbitmq_prometheus rabbitmq_management"
    ports:
      - "127.0.0.1:5674:5672"
      - "127.0.0.1:15674:15672"
      - "127.0.0.1:15694:15692"