services:
  xrpl_ingestor_testnet:
    build:
      context: .
      args:
        BINARY_NAME: xrpl_ingestor
    deploy:
      mode: replicated
      replicas: 4
    environment:
      - NETWORK=testnet

  xrpl_distributor_testnet:
    build:
      context: .
      args:
        BINARY_NAME: xrpl_distributor
    environment:
      - NETWORK=testnet

  xrpl_ticket_creator_testnet:
    build:
      context: .
      args:
        BINARY_NAME: xrpl_ticket_creator
    environment:
      - NETWORK=testnet

  xrpl_includer_testnet:
    build:
      context: .
      args:
        BINARY_NAME: xrpl_includer
    deploy:
      mode: replicated
      replicas: 4
    environment:
      - NETWORK=testnet

  xrpl_subscriber_testnet:
    build:
      context: .
      args:
        BINARY_NAME: xrpl_subscriber
    environment:
      - NETWORK=testnet

  redis_devnet:
    image: redis:alpine
    container_name: redis_devnet
    ports:
      - "127.0.0.1:6379:6379"

  rabbitmq_devnet:
    image: rabbitmq:3-management
    container_name: rabbitmq_devnet
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"

  redis_testnet:
    image: redis:alpine
    container_name: redis_testnet
    ports:
      - "127.0.0.1:6380:6379"

  rabbitmq_testnet:
    image: rabbitmq:3-management
    container_name: rabbitmq_testnet
    ports:
      - "127.0.0.1:5673:5672"
      - "127.0.0.1:15673:15672"

  redis_mainnet:
    image: redis:alpine
    container_name: redis_mainnet
    ports:
      - "127.0.0.1:6380:6379"

  rabbitmq_mainnet:
    image: rabbitmq:3-management
    container_name: rabbitmq_mainnet
    ports:
      - "127.0.0.1:5674:5672"
      - "127.0.0.1:15674:15672"