services:
  xrpl_ingestor:
    build:
      context: .
      args:
        BINARY_NAME: xrpl_ingestor
    container_name: xrpl_ingestor_${NETWORK}_${INSTANCE_ID}
    environment:
      - NETWORK=${NETWORK}
      - INSTANCE_ID=${INSTANCE_ID}

  xrpl_distributor:
    build:
      context: .
      args:
        BINARY_NAME: xrpl_distributor
    container_name: xrpl_distributor_${NETWORK}_${INSTANCE_ID}
    environment:
      - NETWORK=${NETWORK}
      - INSTANCE_ID=${INSTANCE_ID}

  xrpl_ticket_creator:
    build:
      context: .
      args:
        BINARY_NAME: xrpl_ticket_creator
    container_name: xrpl_ticket_creator_${NETWORK}_${INSTANCE_ID}
    environment:
      - NETWORK=${NETWORK}
      - INSTANCE_ID=${INSTANCE_ID}

  xrpl_includer:
    build:
      context: .
      args:
        BINARY_NAME: xrpl_includer
    container_name: xrpl_includer_${NETWORK}_${INSTANCE_ID}
    environment:
      - NETWORK=${NETWORK}
      - INSTANCE_ID=${INSTANCE_ID}

  xrpl_subscriber:
    build:
      context: .
      args:
        BINARY_NAME: xrpl_subscriber
    container_name: xrpl_subscriber_${NETWORK}_${INSTANCE_ID}
    environment:
      - NETWORK=${NETWORK}
      - INSTANCE_ID=${INSTANCE_ID}

  redis_devnet:
    image: redis:alpine
    container_name: redis_devnet
    ports:
      - "127.0.0.1:6379:6379"

  rabbitmq_devnet:
    image: rabbitmq:3-management
    container_name: rabbitmq_devnet
    ports:
      - "127.0.0.1:5672:5672"
      - "127.0.0.1:15672:15672"

  redis_testnet:
    image: redis:alpine
    container_name: redis_testnet
    ports:
      - "127.0.0.1:6380:6379"

  rabbitmq_testnet:
    image: rabbitmq:3-management
    container_name: rabbitmq_testnet
    ports:
      - "127.0.0.1:5673:5672"
      - "127.0.0.1:15673:15672"

  redis_mainnet:
    image: redis:alpine
    container_name: redis_mainnet
    ports:
      - "127.0.0.1:6380:6379"

  rabbitmq_mainnet:
    image: rabbitmq:3-management
    container_name: rabbitmq_mainnet
    ports:
      - "127.0.0.1:5674:5672"
      - "127.0.0.1:15674:15672"