[package]
name = "ton_types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tonlib-core = { workspace = true }
tracing = { workspace = true }
serde_with = "3.14.0"

[lints]
workspace = true
