openapi: 3.0.0
info:
  title: Payload Cache API
  description: A simple API for storing and retrieving payloads by keccak256 hash.
  version: 0.1.0

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /payload:
    post:
      summary: Store a payload
      description: >
        Accepts a payload as the request body and computes
        its keccak256 hash. The payload is stored in memory under that hash.
      operationId: storePayload
      security:
        - BearerAuth: []
      requestBody:
        description: The payload to store
        required: true
        content:
          text/plain:
            schema:
              type: string
              description: Hex-encoded payload (e.g., "010203ab...").
      responses:
        '200':
          description: Successfully stored the payload
          content:
            application/json:
              schema:
                type: object
                properties:
                  hash:
                    type: string
                    description: Keccak256 hash (hex) of the stored payload
        '403':
          description: Forbidden - invalid or missing Bearer token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Forbidden - invalid or missing token
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Not found
    get:
      summary: Retrieve a payload
      description: >
        Given a valid hash (via `?hash=...`), returns the stored payload.
        If the hash is not found, returns a 404.
      operationId: getPayload
      security:
        - BearerAuth: []
      parameters:
        - name: hash
          in: query
          required: true
          description: The keccak256 hash of the payload
          schema:
            type: string
      responses:
        '200':
          description: Successfully retrieved the payload
          content:
            text/plain:
              schema:
                type: string
                description: The original hex-encoded payload
        '403':
          description: Forbidden - invalid or missing Bearer token
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Forbidden - invalid or missing token
        '404':
          description: Not found - no matching payload for the given hash
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Not found

security:
  - BearerAuth: []
