name: Deploy Relayer

concurrency:
  group: deploy-relayer

on:
  push:
    branches:
      - deploy-devnet-xrpl
      - deploy-devnet-ton

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.27.0

      - name: Parse branch
        id: parse
        run: |
          REF="${{ github.event.ref }}"
          BRANCH="${REF##*/}"
          IFS='-' read -r PREFIX ENVIRONMENT CHAIN <<< "$BRANCH"
          echo "environment=$ENVIRONMENT" >> "$GITHUB_OUTPUT"
          echo "chain=$CHAIN" >> "$GITHUB_OUTPUT"

      - name: Configure AWS (OIDC)
        if: env.ACT != 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/GithubActions

      - name: Configure AWS (keys for local act)
        if: env.ACT == 'true'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: ${{ inputs.AWS_ACCOUNT_ID }}

      - name: Build image
        run: |
          ENVIRONMENT="${{ steps.parse.outputs.environment }}"
          CHAIN="${{ steps.parse.outputs.chain }}"
          TAG="relayer/${CHAIN}-${ENVIRONMENT}:${GITHUB_RUN_NUMBER}"
          REPOSITORY="${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com"
          docker build -f Dockerfile.${CHAIN} -t ${REPOSITORY}/${TAG} .
          docker push ${REPOSITORY}/${TAG}
          echo "Pushed ${TAG} to ${REPOSITORY}"
